### PR TITLE
Rough Draft of Database structure

### PR DESCRIPTION
**Pull request by Syst3mz**
I went ahead and dumped a ER diagram for the structure of the database into the readme.md, and the code used to generate it from into 

you can view the actual branch readme [here](https://github.com/RioParsons/012-02-Group-Project/tree/database-structure)

When I was thinking about having multiple roles, since we are only having 2 I think the way I set up the database makes sense because the presence of a user's id in the owners table makes them an owner, instead of having two separate tables but let me know what you think.

### CODE REVIEW

**Review by RioParsons — COMMENTED** [review]
I don't think we need all of the intermediary tables like user_to_rating, restaurant_to_rating,  and owner_to_restaurant.  I took a database management systems class a while ago where we did a lot of ERD design, and I think that we can cut out the intermediary tables. 
In the movies database, we needed intermediary tables like movies_to_actors because each movie could have multiple actors and each actor could be in multiple movies. However, each rating only has one user, so I don't think we need a user_to_rating table. The same goes for the other 'to' tables. I could be wrong, but I think it should look something like this: 
cuisine companion

**Comment by Haydenjmoll** [comment]
I don't know much about ERD database design, but if we want to, we could model it like the lab 7 database. The lab has the following tables: user info, trails, reviews, images, trails to reviews, and reviews to images. 

For our use case, I see something like Rio's database making sense with the fewer tables since ratings only should have one reviewer, but I do see both ways to look at the owner-to-restaurant relation. The first is with a restaurant having multiple users with an owner account (in this case, we would need the intermediate table). The other assumes that each restaurant can only have one owner account, so we wouldn't need the restaurant-to-owner table.

**Comment by Syst3mz** [comment]
I think that works, yeah. Thanks for helping Hayden. Ill get to work on making `create.sql` and `insert.sql`

**Comment by Syst3mz** [comment]
Actually can't a user have multiple reviews? so a users to review table is needed?

**Comment by Syst3mz** [comment]
im going to merge this in to close this branch, we can work on it more if necessary

**Pull request merged**
